### ISSUE TITLE
Got a TypeError: `sequence item 1: expected string, exceptions.IndexError found`

### ISSUE THREAD

**Issue by bumaociyuan** [loggerhead/Easy-Karabiner#5]
```
$ easy_karabiner
Traceback (most recent call last):
  File "/usr/local/bin/easy_karabiner", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/easy_karabiner/main.py", line 79, in main
    print_error(e)
  File "/Library/Python/2.7/site-packages/easy_karabiner/main.py", line 200, in print_error
    print_message(msg, color='red', err=True)
  File "/Library/Python/2.7/site-packages/easy_karabiner/main.py", line 196, in print_message
    click.secho(msg, fg=color, err=err)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/termui.py", line 393, in style
    return ''.join(bits)
TypeError: sequence item 1: expected string, exceptions.IndexError found
```

my config

```
DEFINITIONS = {
    'EMACS_MODE_IGNORE_APPS': ['X11', 'Terminal', 'Atom', 'iTerm']
}

MAPS = [
    ['ctrl c', 'esc', ['Google Chrome']],
    ['ctrl c', 'esc', ['Sublime Text']],
    ['h', 'left', ['Preview']],
    ['j', 'down', ['Preview']],
    ['k', 'up', ['Preview']],
    ['l', 'right', ['Preview']],
    # ['o', 'cmd +', ['Preview']],
    # ['i', 'cmd -', ['Preview']],
    # ['f', 'cmd 9', ['Preview']],


    ['cmd esc', 'cmd `']
]
```

**Comment by loggerhead** [comment]
What's your system version and Karabiner version? I can't repro your problem in my computer.

**Comment by bumaociyuan** [comment]
![35c7630b-4481-4567-8c98-e8aec5b4b0bb](https://cloud.githubusercontent.com/assets/4977911/19583733/dc1f9d34-9771-11e6-90c8-e3e5099da698.png)

![968c73fb-d0a7-43bc-8371-80b1bed010ea](https://cloud.githubusercontent.com/assets/4977911/19583776/0ed7eace-9772-11e6-9a6a-b95c4c51089d.png)

```
$ python --version
Python 2.7.12
```

**Comment by loggerhead** [comment]
Thank you for feedback. I would test it in recent days (update system need time 😃).

**Comment by bumaociyuan** [comment]
@loggerhead Thanks

**Comment by loggerhead** [comment]
@bumaociyuan I fixed a logging problem, but still can't repro the problem. Could you try the following commands (put your config to file `input.py`), and tell me what's the output?

```
pip install git+git://github.com/loggerhead/Easy-Karabiner.git@dev
easy_karabiner --verbose --string input.py
```

And also, try examples to see if they works or not.

**Comment by bumaociyuan** [comment]
input.py as example in readme

```
DEFINITIONS = {
    'EMACS_MODE_IGNORE_APPS': ['X11', 'Terminal', 'Atom', 'iTerm']
}

MAPS = [
    ['ctrl c', 'esc', ['Google Chrome']],
    ['ctrl c', 'esc', ['Sublime Text']],
    ['h', 'left', ['Preview']],
    ['j', 'down', ['Preview']],
    ['k', 'up', ['Preview']],
    ['l', 'right', ['Preview']],
    # ['o', 'cmd +', ['Preview']],
    # ['i', 'cmd -', ['Preview']],
    # ['f', 'cmd 9', ['Preview']],


    ['cmd esc', 'cmd `']
]
```

```
$ easy_karabiner --verbose --string input.py

executing "input.py"
update aliases from user configuration
generating XML configuration
parsing user configuration
encoding configuration with UTF-8
creating definitions
organizing keymaps
creating XML block from keymaps
list index out of range
```

`list index out of range` is red

**Comment by loggerhead** [comment]
@bumaociyuan It's really not easy to find out the bug, as I cannot repro it 😞 . Anyway, can you try the following examples with the new code (need `pip install` again)? To see which example failed, and what's the output looks like. Then I could narrow down the range of the cause.

``` python
MAPS = [
    ['alt', 'cmd'],
]
```

``` python
MAPS = [
    ['h', 'left', ['Preview']],
]
```

``` python
DEFINITIONS = {
    'EMACS_MODE_IGNORE_APPS': ['Google Chrome']
}
MAPS = [
    ['alt', 'cmd', 'Google Chrome'],
]
```

**Comment by bumaociyuan** [comment]
1

```
Execute "input.py"
Generate XML configuration
<?xml version="1.0" ?>
<root>
  <Easy-Karabiner>0.5.1</Easy-Karabiner>
  <item>
    <name>Easy-Karabiner</name>
    <item>
      <name>Enable</name>
      <identifier>private.easy_karabiner</identifier>
      <block>
        <autogen> __KeyToKey__
          KeyCode::OPTION_L,
          KeyCode::COMMAND_L
        </autogen>
      </block>
    </item>
  </item>
</root>
```

2 

```
Execute "input.py"
Generate XML configuration
Traceback (most recent call last):
  File "/usr/local/bin/easy_karabiner", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/easy_karabiner/main.py", line 79, in main
    print_error(e)
  File "/Library/Python/2.7/site-packages/easy_karabiner/main.py", line 200, in print_error
    print_message(msg, color='red', err=True)
  File "/Library/Python/2.7/site-packages/easy_karabiner/main.py", line 196, in print_message
    click.secho(msg, fg=color, err=err)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/termui.py", line 393, in style
    return ''.join(bits)
TypeError: sequence item 1: expected string, exceptions.IndexError found
```

3

```

Execute "input.py"
Generate XML configuration
<?xml version="1.0" ?>
<root>
  <Easy-Karabiner>0.5.1</Easy-Karabiner>
  <item>
    <name>Easy-Karabiner</name>
    <vkopenurldef>
      <name>KeyCode::VK_OPEN_URL_Google_Chrome</name>
      <url type="file">/Applications/Google Chrome.app</url>
    </vkopenurldef>
    <item>
      <name>Enable</name>
      <identifier>private.easy_karabiner</identifier>
      <block>
        <autogen> __KeyToKey__
          KeyCode::OPTION_L,
          KeyCode::COMMAND_L
        </autogen>
      </block>
    </item>
  </item>
</root>

Invalid definition: `EMACS_MODE_IGNORE_APPS` in {u'EMACS_MODE_IGNORE_APPS': [u'Google Chrome']}

```

**Comment by loggerhead** [comment]
@bumaociyuan Can you update Easy-Karabiner and try the following config again?

``` shell
pip install git+git://github.com/loggerhead/Easy-Karabiner.git@dev
easy_karabiner --verbose --string input.py
```

``` python
MAPS = [
    ['h', 'left', ['Preview']],
]
```

``` python
MAPS = [
    ['alt', 'cmd', ['Preview']],
]
```

**Comment by bumaociyuan** [comment]
```
$ pip install git+git://github.com/loggerhead/Easy-Karabiner.git@dev
easy_karabiner --verbose --string input.py
Collecting git+git://github.com/loggerhead/Easy-Karabiner.git@dev
  Cloning git://github.com/loggerhead/Easy-Karabiner.git (to dev) to /var/folders/z9/zmw09m8x2xs18t_yjrj8sdh80000gn/T/pip-Wb0qAF-build
  Requirement already satisfied (use --upgrade to upgrade): easy-karabiner==0.5.1 from git+git://github.com/loggerhead/Easy-Karabiner.git@dev in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): lxml<4.0.0,>=3.0.0 in /Library/Python/2.7/site-packages (from easy-karabiner==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): click<7.0.0,>=6.0.0 in /usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg (from easy-karabiner==0.5.1)
```

1

```
Execute "input.py"
Generate XML configuration
Traceback (most recent call last):
  File "/usr/local/bin/easy_karabiner", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/easy_karabiner/main.py", line 79, in main
    print_error(e)
  File "/Library/Python/2.7/site-packages/easy_karabiner/main.py", line 200, in print_error
    print_message(msg, color='red', err=True)
  File "/Library/Python/2.7/site-packages/easy_karabiner/main.py", line 196, in print_message
    click.secho(msg, fg=color, err=err)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/termui.py", line 393, in style
    return ''.join(bits)
TypeError: sequence item 1: expected string, exceptions.IndexError found
```

2

```
Execute "input.py"
Generate XML configuration
Traceback (most recent call last):
  File "/usr/local/bin/easy_karabiner", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/easy_karabiner/main.py", line 79, in main
    print_error(e)
  File "/Library/Python/2.7/site-packages/easy_karabiner/main.py", line 200, in print_error
    print_message(msg, color='red', err=True)
  File "/Library/Python/2.7/site-packages/easy_karabiner/main.py", line 196, in print_message
    click.secho(msg, fg=color, err=err)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "/usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/termui.py", line 393, in style
    return ''.join(bits)
TypeError: sequence item 1: expected string, exceptions.IndexError found
```

**Comment by loggerhead** [comment]
@bumaociyuan You are using master branch, not dev. Try those commands:

```
pip uninstall easy_karabiner
git clone https://github.com/loggerhead/Easy-Karabiner.git
git checkout dev
pip install -e .
```

And test again.

**Comment by bumaociyuan** [comment]
```
$ sudo pip install -e .
The directory '/Users/zx/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/zx/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///Users/zx/Downloads/Easy-Karabiner
Requirement already satisfied (use --upgrade to upgrade): lxml<4.0.0,>=3.0.0 in /Library/Python/2.7/site-packages (from easy-karabiner==0.5.1)
Requirement already satisfied (use --upgrade to upgrade): click<7.0.0,>=6.0.0 in /usr/local/lib/python2.7/site-packages/click-6.6-py2.7.egg (from easy-karabiner==0.5.1)
Installing collected packages: easy-karabiner
  Running setup.py develop for easy-karabiner
Successfully installed easy-karabiner
```

1

```
MAPS = [
    ['h', 'left', ['Preview']],
]
```

```
executing "input.py"
update aliases from user configuration
generating XML configuration
parsing user configuration
encoding configuration with UTF-8
creating definitions
organizing keymaps
creating XML block from keymaps
list index out of range
Traceback (most recent call last):
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/main.py", line 57, in main
    xml_str = gen_config(configs)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/main.py", line 136, in gen_config
    return Generator(maps, definitions).to_str()
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/basexml.py", line 96, in to_str
    xml_str = self.to_format_str(self.to_xml(), pretty_text=pretty_text)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/generator.py", line 72, in to_xml
    blocks, definitions = parse.parse(self.maps, self.definitions)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/parse.py", line 32, in parse
    block_objs = create_blocks(filters_keymaps_table)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/parse.py", line 103, in create_blocks
    factory.define_filters(raw_filters)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/factory.py", line 28, in define_filters
    FilterCreater.define(val)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/factory.py", line 102, in define
    device_ids = osxkit.get_peripheral_info(val)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/osxkit.py", line 163, in get_peripheral_info
    get_peripheral_info.infos = get_all_peripheral_info()
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/osxkit.py", line 130, in get_all_peripheral_info
    item = [v for k, v in info_tree['Bluetooth'].items() if k.startswith('Devices')][0]
IndexError: list index out of range
```

2

```
MAPS = [
    ['alt', 'cmd', ['Preview']],
]
```

```
executing "input.py"
update aliases from user configuration
generating XML configuration
parsing user configuration
encoding configuration with UTF-8
creating definitions
organizing keymaps
creating XML block from keymaps
list index out of range
Traceback (most recent call last):
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/main.py", line 57, in main
    xml_str = gen_config(configs)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/main.py", line 136, in gen_config
    return Generator(maps, definitions).to_str()
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/basexml.py", line 96, in to_str
    xml_str = self.to_format_str(self.to_xml(), pretty_text=pretty_text)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/generator.py", line 72, in to_xml
    blocks, definitions = parse.parse(self.maps, self.definitions)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/parse.py", line 32, in parse
    block_objs = create_blocks(filters_keymaps_table)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/parse.py", line 103, in create_blocks
    factory.define_filters(raw_filters)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/factory.py", line 28, in define_filters
    FilterCreater.define(val)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/factory.py", line 102, in define
    device_ids = osxkit.get_peripheral_info(val)
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/osxkit.py", line 163, in get_peripheral_info
    get_peripheral_info.infos = get_all_peripheral_info()
  File "/Users/zx/Downloads/Easy-Karabiner/easy_karabiner/osxkit.py", line 130, in get_all_peripheral_info
    item = [v for k, v in info_tree['Bluetooth'].items() if k.startswith('Devices')][0]
IndexError: list index out of range
```

**Comment by loggerhead** [comment]
@bumaociyuan The problem should be fixed now, try again?

**Comment by bumaociyuan** [comment]
@loggerhead OK

**Comment by bumaociyuan** [comment]
@loggerhead I've tried reinstall easy_karabiner. Still not working

**Comment by loggerhead** [comment]
@bumaociyuan Do you use dev branch? What's the error?

**Comment by bumaociyuan** [comment]
@loggerhead Thank you very much. It works fine.

**Comment by loggerhead** [comment]
You are welcome 😃. The problem has fixed in v0.5.2.
